### ISSUE TITLE
Fix chair collision box

### ISSUE THREAD

**Issue by bengardner** [theraven262/minetest-furnituregen#3]
I'm trying to get NPCs to sit on a chair, bed, etc.

The chairs from "ts_furniture", such as "ts_furniture:default_wood_chair" work great.

The chairs from this "furniture" mod don't work.  The NPC falls through and sits on the ground.
![chair_broken_s](https://user-images.githubusercontent.com/83918/206584279-58e5bccb-88b4-4ea9-9b4e-769feaa2856a.png)

From left to right, we have a `furniture:chair_pine_wood`, `furniture:chair_glass_glass`, `ts_furniture:default_wood_chair` and
`furniture:chair_thick_desert_stone`.

The problem is that the `collisionbox` is too tall.  When the NPC sits in the node, it already is inside the collision box and so falls down to the node below.
The ts_furniture chair uses `nodebox` to build the chair, so the `collisionbox` is correct.

Adding an optional `cbox` item to `furniture.types` and altering `furniture.assemble_node` to use that, if present fixes the issue for me.
![chair_fixed_s](https://user-images.githubusercontent.com/83918/206584292-40a594ef-a927-43ec-a9ce-0d1ce6e096a9.png)

The pull request to fix this is #2 .

**Comment by theraven262** [comment]
Merged #2
